config/routes.rb
  Rails.application.routes.draw do

  scope "/students" do
    resources :grades
    resources :achievements
  end

  scope "/teachers" do
    get "/grades/:id" =>"teachers#getGrade"
    get "/achievements/:id" =>"teachers#getAchievement"
  end

  get "/students" => "students#index"
  get "/teachers" => "teachers#index"
  get "/students/edit-detail" => "students#edit_detail"
  post"/students/edit-detail" => "students#update"
  root "home#index"
    devise_for :students, :controllers => { :sessions => "sessions" ,:registrations =>"registrations"}
    devise_for :teachers, :controllers => { :sessions => "sessions" ,:registrations =>"registrations"}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'teachers/index'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	belongs_to :stud
	validates :title,:description,:achievment_date,presence:true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :stud
  validates :subject,:grade,:examdate,presence:true
end

app/models/stud.rb
class Stud < ActiveRecord::Base
  validates :firstname,:lastname,:class_name,:hobby,presence:true
  belongs_to :user
  has_many :grades
  has_many :achievements
end

app/models/student.rb
class Student < User
  # devise :database_authenticatable,:validatable
  
end

app/models/teacher.rb
class Teacher < User

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :stud
  validates :username,presence: true,length:{minimum:5},uniqueness:{case_sensitive: true}
  validates :email,presence: true,uniqueness:true
  validates :usertype,presence: true
  # self.abstract_class = true



end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_student!
  def index
    @achievements=current_student.stud.achievements
    render json:@achievements
  end

  def create
    @achievement=current_student.stud.achievements.create(achievement_params)
    if @achievement.errors.any?
      render json:@achievement.errors.to_a ,status: :not_found
    else
        index
    end
  end

  def destroy
    Achievement.find_by(:id=>params[:id]).destroy
    index
  end

  def update
    @achievement=Achievement.find_by(id:params[:id])
    @achievement.update_attributes(achievement_params)
    if @achievement.errors.any?
      render json:@achievement.errors.to_a ,status: :not_found
    else
        index
    end
  end

  private
    def achievement_params
      params.require(:achievement).permit(:title,:description,:achievment_date)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  def after_sign_in_path_for(resource)
    if resource.usertype == "teacher"
      return  teachers_url
    elsif resource.usertype == "student"
      return students_url
    end
  end

  protected


    def layout_by_resource
      if devise_controller? && resource_name == :student
        "student"
      elsif devise_controller? && resource_name == :teacher
        "teacher"
      else
        "application"
      end
    end

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  # layout "student", :only => [:show, :index,:new,:edit]
  layout false

  # skip_before_action :verify_authenticity_token

  before_action :authenticate_student!
  def index
    @grades=current_student.stud.grades
    render json: @grades
  end


  def new
  end

  def create
        @grade=current_student.stud.grades.create(grade_params)
        if @grade.errors.any?
            render json:@grade.errors.to_a ,status: :not_found
        else
            index
        end
  end

  def show
  end

  def update
      @grade=Grade.find(params[:grade][:id])
      @grade.update_attributes(grade_params)
      if @grade.errors.any?
        render json:@grade.errors.to_a ,status: :not_found
      else
        index
      end
  end

  def destroy
    @grade=Grade.find_by(:id=>params[:id])
    @grade.destroy()
    index
  end

private
  def grade_params
     params.require(:grade).permit(:subject, :grade,:examdate)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "student"
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    def create
      role=params.keys[2]
        @user = User.find_by_email(params[role][:email])
        if @user != nil
          if !@user || @user.usertype!=role
            flash[:danger] = " Access denied."
              redirect_to root_url
          else
            super
          end
        else
            flash[:warning] = "Incorrect email or password"
            redirect_to root_url
        end
    end


    def after_sign_out_path_for(resource)
        if resource == :student
          puts "Student Sign Out"
          return student_session_url
        elsif resource == :teacher
          return teacher_session_url
        end
    end

    def destroy
      super
    end
  end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout "student"
  before_action :authenticate_student!
  def index
  end

  def show
  end

  def edit_detail
    # @stud=Stud.where(:user_id=>current_student.id)
    @stud=current_student.stud
    render "editdetail"
  end

  def update
    @sutd=current_student.stud
    if @sutd.update_attributes(studs_params)
      redirect_to students_edit_detail_path,flash: {success: "Updated Successfully "}
    else
      redirect_to students_edit_detail_path,flash:{alert:"Unable to Update Detail"}
    end
  end


  private
    def studs_params
      params.require(:stud).permit(:firstname,:lastname,:class_name,:hobby)
    end
end

app/controllers/studs_controller.rb
class StudsController < ApplicationController

  def create

  end

  private
    def stud_params
      params.require(:stud).permit(:user_id,:class_name,:hobby)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  layout "teacher"
  before_action :authenticate_teacher!
  def index
    @students=Stud.all
  end

  def getGrade
    @grade=Grade.where(stud_id:params[:id])
    render json:@grade
  end

  def getAchievement
    @achievement=Achievement.where(stud_id:params[:id])
    render json:@achievement
  end

  def edit
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
   return '' if resource.errors.empty?

     messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.uniq.join
       html = <<-HTML
               <div class="alert alert-danger">
                    #{messages}
              </div>
       HTML

     html.html_safe
 end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studs_helper.rb
module StudsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/achievements/_achivements_form.html.erb
<form class="form" ng-submit="addAchievement(newAchievement)" role="form">
  <div class="form-group">
      <label for="title">Title</label>
      <input type="text" name="title"   ng-model="newAchievement.title" class="form-control" >
  </div>

  <div class="form-group">
      <label for="Description">Description</label>
      <input type="text" name="description"  ng-model="newAchievement.description" class="form-control" >
  </div>


  <div class="form-group">
      <label for="date">Date</label>
      <input type="date" name="date" ng-model="newAchievement.achievment_date" class="form-control">
  </div>

  <div class="form-group">
    <input type="submit" class="form-control btn btn-success" value="Save">
  </div>
</form>

app/views/achievements/_achivements_list.html.erb
<ul class="list-group">
    <li class="list-group-item" ng-repeat="achievement in achievements">
        <h4 class="list-group-item-heading">
          {{achievement.title}}
        </h4>
        <p class="list-group-item-text">
          {{achievement.description}}
        </p>
        <p>
            {{achievement.achievment_date|date}}
        </p>
        <button type="button" class="btn btn-info" ng-click="updateAchievement(achievement)">Update</button>
        <button type="button" class="btn btn-danger" ng-click="deleteAchievement(achievement)">Delete</button>
    </li>
</ul>

app/views/achievements/index.html.erb
<div class="row" ng-controller="achievementController">
  <div class="col-md-8">
  </div>

  <div class="col-md-4">
    <form class="form" role="form">
      <div class="form-group">

      </div>
    </form>
  </div>

</div>

app/views/achievements/show.html.erb
<div class="row"  ng-controller="achievementController">
  <div class="col-md-9">
        <div flash-message="5000"></div>
        <%= render :partial => "achivements_list" %>
    </div>

  <div class="col-md-3">
    <div class="alert alert-danger" ng-show="errors!=null" >
      <p ng-repeat="val in errors">
        {{$index+1}}. {{val}}
      </p>
    </div>

      <%= render :partial=>"achivements_form" %>
    </div>

</div>

app/views/grades/_grade_form.html.erb
<form class="form" name="gradeForm" ng-submit="addGrade(newGrade)"  method="post">

    <div class="alert alert-danger" ng-show="errors!=null" >
      <p ng-repeat="val in errors">
        {{$index+1}}. {{val}}
      </p>
    </div>
  <div class="form-group"  >
    <label for="">Subject</label>
    <input type="text" class="form-control"  ng-model="newGrade.subject" name="subject" value="" >
  </div>
  <div class="form-group">
    <label for="">Grade</label>
    <input type="text" class="form-control"  ng-model="newGrade.grade" name="grade" value="" >
  </div>
  <div class="form-group">
    <label for="">Examdate</label>
    <input type="date" class="form-control"  ng-model="newGrade.examdate" name="examdate" value="" >
  </div>
  <div class="form-group">
    <input type="submit" class="form-control btn btn-success" value="Save" >
  </div>
</form>

app/views/grades/_grade_list.html.erb
<ul>
  <li class="list-group-item" ng-repeat="grade in grades">
    <p class="list-heading">Id:{{grade.id}}</p>
    <p class="list-heading">Subject:{{grade.subject}}</p>
    <p class="list-heading">Grade:{{grade.grade}}</p>
    <p> Exam Date :{{grade.examdate|date}}</p>
    <div>
        <button type="button" class="btn btn-danger" ng-model="grade" ng-click="deleteGrade(grade)">Delete</button>
        <button type="button" class="btn btn-info" ng-click="updateGrade(grade)">Update</button>
    </div>
  </li>
</ul>

app/views/grades/show.html.erb
<div class="row" ng-controller="studentControl">
  <div class="col-md-3" >
    <%= render :partial=>"grade_form" %>
  </div>

  <div class="col-md-9">
    <div flash-message="5000"></div>
    <%= render :partial=>"grade_list" %>
  </div>
</div>

app/views/students/editdetail.html.erb
<div class="page-header">
  <h2 class="text-center">Update Detail</h2>
</div>
<div class="col-md-6 col-md-offset-3">
  <%= form_for  :stud do |f| %>
  <div class="form-group">
    <%= f.label :firstname %>
    <%= f.text_field  :firstname ,class:"form-control" %>
  </div>
    <div class="form-group">
      <%= f.label :lastname %>
      <%= f.text_field  :lastname ,class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :class_name %>
      <%= f.text_field  :class_name ,class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :hobby %>
      <%= f.text_field  :hobby ,class:"form-control" %>
    </div>


    <div class="form-group">
        <%= f.submit "Update Detail" ,class:"col-md-12 btn btn-warning" ,style:"margin-bottom:2%" %>
    </div>
    <% end %>
</div>

app/views/students/index.html.erb
<div class="row" ng-app="studentApp" >
  <div class="form-group col-md-6" >
    <%=link_to "Manage Grades","#grades",class:"btn btn-info form-control" ,style:"margin-top:2%"%>
  </div>

  <div class="form-group col-md-6" >
    <%=link_to "Manage Achivment","#achievement",class:"btn btn-warning form-control" ,style:"margin-top:2%"%>
  </div>
    <div ng-view>
    </div>
</div>

app/views/students/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name),class:"btn btn-default" %><br />
<% end -%>


<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>

<%= link_to "Forgot your password?", new_password_path(resource_name),class:"btn btn-default col-md-12",style:"margin-bottom:3%" %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/students/template/_footer.html.erb
<div class="footer-bg">
<div class="wrap">
<div class="footer">
    <div class="f_grid">
    <div class="social">
        <ul class="follow_icon">
          <li><a href="#" style="opacity: 1;"><img src="/images/fb.png" alt=""></a></li>
          <li><a href="#" style="opacity: 1;"><img src="/images/g+.png" alt=""></a></li>
          <li><a href="#" style="opacity: 1;"><img src="/images/tw.png" alt=""></a></li>
        </ul>
      </div>
    </div>
    <div class="f_grid1">
      <ul class="f_nav">
        <li><a href="index.html">Home</a></li>
        <li><a href="/teachers/sign_in">Sign in as Teacher</a></li>
      </ul>
      <div class="clear"></div>
    </div>
    <div class="f_logo">
      <a href="<%=root_url%>"><img src="/images/logo2.png" alt=""></a>
    </div>
    <div class="clear"></div>
</div>
</div>
</div>

app/views/students/template/_header.html.erb
<div class="header-bg">
<div class="wrap">
  <div class="header">
    <div class="logo">
          <a href="<%=root_url%>"><img src="/images/logo1.png"> </a>
     </div>
    <div class="menu">
  <ul class='kwicks kwicks-horizontal'>
      <li><a href="<%=root_url%>">Home</a></li>
        <% if student_signed_in? %>
         <li><a href="/students/edit"><%=current_student.username%></a><																																																								/li>
         <li><%= link_to('sign out', destroy_student_session_path) %></li>
         <li><a href="/students">Assets</a></li>
        <%else%>
          <li><a href="/students/sign_in">Sign in</a></li>
          <li><a href="/students/sign_up">Sign up</a></li>
        <%end%>
  </ul>
   </div>
   <div class="clear"></div>
  </div>
</div>
</div>

app/views/students/template/_messages.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>" style="margin-top:2%">
      <%= value %>
    </div>
  <% end %>
</div>

app/views/teachers/edit.html.erb
<h1>Teachers#edit</h1>
<p>Find me in app/views/teachers/edit.html.erb</p>

app/views/teachers/index.html.erb
<div class="row" ng-app="teacherApp" ng-controller="teacherController">

  <div class="col-md-8" >
  <ul class="nav nav-tabs" role="tablist">
   <li role="presentation"  class="active"><a href="#grades" aria-controls="grades" role="tab" data-toggle="tab" aria-expanded="true">Grades</a></li>
   <li role="presentation" ><a href="#achievements" aria-controls="achievements" role="tab" data-toggle="tab">Achievements</a></li>
 </ul>
<div class="tab-content" >
  <div role="tabpanel"   class="tab-pane fade in active" id="grades">
    <ul class="list-group">
      <li class="list-group-item" ng-repeat="grade in grades">
        <h4 class="list-group-item-heading"><b>Subject</b> : {{grade.subject}}</h4>
        <p class="list-group-item-text"><b>Grade</b> : {{grade.grade}}</p>
        <p class="list-group-item-text text-muted"><b>Exam Date</b> :{{grade.examdate|date}}</p>
      </li>
    </ul>
  </div>

  <div role="tabpanel" class="tab-pane fade" id="achievements">
    <ul class="list-group">
      <li class="list-group-item" ng-repeat="achievement in achievements">
        <h4 class="list-group-item-heading"><b>Title</b> : {{achievement.title}}</h4>
        <p class="list-group-item-text"><b>Description</b> : {{achievement.description}}</p>
        <p class="list-group-item-text text-muted"><b>Date</b> :{{achievement.achievment_date|date}}</p>
      </li>
    </ul>
    </div>
</div>
  </div>

  <div class="col-md-4" >
    <div class="panel panel-primary">
      <div class="panel-heading">
        Students
      </div>
      <div class="panel-body" >
        <ul class="list-group">
          <% if !@students.blank? %>
            <% for @user in @students %>
              <li class="list-group-item"  ng-class="{active: id===<%=@user.id%>}" ng-click="getDetail(<%=@user.id%>)" >
                <%= @user.firstname+" "+@user.lastname %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/teachers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/teachers/show.html.erb
<%= @users.inspect %>