config/routes.rb
  Rails.application.routes.draw do

  scope "/students" do
    resources :grades
    resources :achievements
  end

  scope "/teachers" do
    get "/grades/:id" =>"teachers#getGrade"
    get "/achievements/:id" =>"teachers#getAchievement"
  end

  get "/students" => "students#index"
  get "/teachers" => "teachers#index"
  get "/students/edit-detail" => "students#edit_detail"
  post"/students/edit-detail" => "students#update"
  root "home#index"
    devise_for :students, :controllers => { :sessions => "sessions" ,:registrations =>"registrations"}
    devise_for :teachers, :controllers => { :sessions => "sessions" ,:registrations =>"registrations"}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'teachers/index'

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
	belongs_to :stud
	validates :title,:description,:achievment_date,presence:true
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :stud
  validates :subject,:grade,:examdate,presence:true
end

app/models/stud.rb
class Stud < ActiveRecord::Base
  validates :firstname,:lastname,:class_name,:hobby,presence:true
  belongs_to :user
  has_many :grades
  has_many :achievements
end

app/models/student.rb
class Student < User
  # devise :database_authenticatable,:validatable
  
end

app/models/teacher.rb
class Teacher < User

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :stud
  validates :username,presence: true,length:{minimum:5},uniqueness:{case_sensitive: true}
  validates :email,presence: true,uniqueness:true
  validates :usertype,presence: true
  # self.abstract_class = true



end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  # layout "student", :only => [:show, :index,:new,:edit]
  layout false

  # skip_before_action :verify_authenticity_token

  before_action :authenticate_student!
  def index
    @grades=current_student.stud.grades
    render json: @grades
  end


  def new
  end

  def create
        @grade=current_student.stud.grades.create(grade_params)
        if @grade.errors.any?
            render json:@grade.errors.to_a ,status: :not_found
        else
            index
        end
  end

  def show
  end

  def update
      @grade=Grade.find(params[:grade][:id])
      @grade.update_attributes(grade_params)
      if @grade.errors.any?
        render json:@grade.errors.to_a ,status: :not_found
      else
        index
      end
  end

  def destroy
    @grade=Grade.find_by(:id=>params[:id])
    @grade.destroy()
    index
  end

private
  def grade_params
     params.require(:grade).permit(:subject, :grade,:examdate)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout "student"
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    def create
      role=params.keys[2]
        @user = User.find_by_email(params[role][:email])
        if @user != nil
          if !@user || @user.usertype!=role
            flash[:danger] = " Access denied."
              redirect_to root_url
          else
            super
          end
        else
            flash[:warning] = "Incorrect email or password"
            redirect_to root_url
        end
    end


    def after_sign_out_path_for(resource)
        if resource == :student
          puts "Student Sign Out"
          return student_session_url
        elsif resource == :teacher
          return teacher_session_url
        end
    end

    def destroy
      super
    end
  end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  layout "student"
  before_action :authenticate_student!
  def index
  end

  def show
  end

  def edit_detail
    # @stud=Stud.where(:user_id=>current_student.id)
    @stud=current_student.stud
    render "editdetail"
  end

  def update
    @sutd=current_student.stud
    if @sutd.update_attributes(studs_params)
      redirect_to students_edit_detail_path,flash: {success: "Updated Successfully "}
    else
      redirect_to students_edit_detail_path,flash:{alert:"Unable to Update Detail"}
    end
  end


  private
    def studs_params
      params.require(:stud).permit(:firstname,:lastname,:class_name,:hobby)
    end
end

app/controllers/studs_controller.rb
class StudsController < ApplicationController

  def create

  end

  private
    def stud_params
      params.require(:stud).permit(:user_id,:class_name,:hobby)
    end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
   return '' if resource.errors.empty?

     messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.uniq.join
       html = <<-HTML
               <div class="alert alert-danger">
                    #{messages}
              </div>
       HTML

     html.html_safe
 end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/studs_helper.rb
module StudsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
<head>
<title>The Knowledge Website Template | Home :: w3layouts</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
<%= yield %>

</body>
</html>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "School" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "student", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "student" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
    <script type='text/javascript'>
  	$(function() {
  	 $('.kwicks').kwicks({
    		maxSize : 250,
    		spacing : 4,
    		behavior: 'menu'
  		});


	});
  </script>
  </head>
  <body>
    <%= render :partial=>"students/template/header" %>
    <%= render :partial=>"students/template/messages" %>
      <div class="container">
        <%= yield %>
      </div>
    <%= render :partial=>"students/template/footer" %>
</body>
</html>

app/views/layouts/teacher.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "School" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "teacher", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "teacher" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">School</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% if teacher_signed_in?%>
              <li><%= link_to "Sign out",destroy_teacher_session_path  %></li>
              <li><%= link_to "Edit Detail", edit_teacher_registration_path  %></li>
            <%else%>
              <li><%= link_to "Sign in", new_teacher_session_path  %></li>
              <li><%= link_to "Sign up", new_teacher_registration_path  %></li>
            <%end%>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
      </div><!--/row-->


      <footer class="navbar-inverse navbar-fixed-bottom" style="padding-top:1%">
        <div class="container">
          <div class="col-md-6">
            <p class="text-muted text-left"><a href="<%= root_url%>" style="text-decoration:none">Student's Desk</a></p>
          </div>
          <div class="col-md-6">
            <p class="text-muted text-center">&copy;2016</p>
          </div>
        </div>
      </footer>
    </div> <!-- /container -->

  </body>
</html>